### ISSUE TITLE
Got `504: GATEWAY_TIMEOUT` sometimes

### ISSUE THREAD

**Issue by hurifajri** [mazipan/graphql-pokeapi#38]
This site (https://kepomon.jadi.dev) previously used GraphCDN endpoint version (https://graphql-pokeapi.graphcdn.app) and got `504: GATEWAY_TIMEOUT` sometimes.
It runs good once switched to the origin endpoint version (https://graphql-pokeapi.vercel.app/api/graphql)
Any idea?

**Comment by mazipan** [comment]
My guess is because the GraphCDN version is not sync with the latest code on master.
But please try again, and let me know if you still facing same errors
